/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedProjectsProjectIdDashboardImport } from './routes/_authenticated/projects/$projectId/dashboard'
import { Route as AuthenticatedProjectsProjectIdSummariesRouteImport } from './routes/_authenticated/projects/$projectId/summaries/route'
import { Route as AuthenticatedProjectsProjectIdSnippetsRouteImport } from './routes/_authenticated/projects/$projectId/snippets/route'
import { Route as AuthenticatedProjectsProjectIdTodosIndexImport } from './routes/_authenticated/projects/$projectId/todos/index'
import { Route as AuthenticatedProjectsProjectIdSummariesIndexImport } from './routes/_authenticated/projects/$projectId/summaries/index'
import { Route as AuthenticatedProjectsProjectIdSnippetsIndexImport } from './routes/_authenticated/projects/$projectId/snippets/index'
import { Route as AuthenticatedProjectsProjectIdDailyNotesIndexImport } from './routes/_authenticated/projects/$projectId/daily-notes/index'
import { Route as AuthenticatedProjectsProjectIdSnippetsNewSnippetImport } from './routes/_authenticated/projects/$projectId/snippets/new-snippet'
import { Route as AuthenticatedProjectsProjectIdDailyNotesNoteIdImport } from './routes/_authenticated/projects/$projectId/daily-notes/$noteId'
import { Route as AuthenticatedProjectsProjectIdSummariesSummaryIdIndexImport } from './routes/_authenticated/projects/$projectId/summaries/$summaryId/index'
import { Route as AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexImport } from './routes/_authenticated/projects/$projectId/snippets/$snippetId/index'
import { Route as AuthenticatedProjectsProjectIdSnippetsSnippetIdEditImport } from './routes/_authenticated/projects/$projectId/snippets/$snippetId/edit'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProjectsProjectIdDashboardRoute =
  AuthenticatedProjectsProjectIdDashboardImport.update({
    id: '/projects/$projectId/dashboard',
    path: '/projects/$projectId/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdSummariesRouteRoute =
  AuthenticatedProjectsProjectIdSummariesRouteImport.update({
    id: '/projects/$projectId/summaries',
    path: '/projects/$projectId/summaries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdSnippetsRouteRoute =
  AuthenticatedProjectsProjectIdSnippetsRouteImport.update({
    id: '/projects/$projectId/snippets',
    path: '/projects/$projectId/snippets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdTodosIndexRoute =
  AuthenticatedProjectsProjectIdTodosIndexImport.update({
    id: '/projects/$projectId/todos/',
    path: '/projects/$projectId/todos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdSummariesIndexRoute =
  AuthenticatedProjectsProjectIdSummariesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdSummariesRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdSnippetsIndexRoute =
  AuthenticatedProjectsProjectIdSnippetsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdSnippetsRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdDailyNotesIndexRoute =
  AuthenticatedProjectsProjectIdDailyNotesIndexImport.update({
    id: '/projects/$projectId/daily-notes/',
    path: '/projects/$projectId/daily-notes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute =
  AuthenticatedProjectsProjectIdSnippetsNewSnippetImport.update({
    id: '/new-snippet',
    path: '/new-snippet',
    getParentRoute: () => AuthenticatedProjectsProjectIdSnippetsRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute =
  AuthenticatedProjectsProjectIdDailyNotesNoteIdImport.update({
    id: '/projects/$projectId/daily-notes/$noteId',
    path: '/projects/$projectId/daily-notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute =
  AuthenticatedProjectsProjectIdSummariesSummaryIdIndexImport.update({
    id: '/$summaryId/',
    path: '/$summaryId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdSummariesRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute =
  AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexImport.update({
    id: '/$snippetId/',
    path: '/$snippetId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdSnippetsRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute =
  AuthenticatedProjectsProjectIdSnippetsSnippetIdEditImport.update({
    id: '/$snippetId/edit',
    path: '/$snippetId/edit',
    getParentRoute: () => AuthenticatedProjectsProjectIdSnippetsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/projects/$projectId/snippets': {
      id: '/_authenticated/projects/$projectId/snippets'
      path: '/projects/$projectId/snippets'
      fullPath: '/projects/$projectId/snippets'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSnippetsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/summaries': {
      id: '/_authenticated/projects/$projectId/summaries'
      path: '/projects/$projectId/summaries'
      fullPath: '/projects/$projectId/summaries'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSummariesRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/dashboard': {
      id: '/_authenticated/projects/$projectId/dashboard'
      path: '/projects/$projectId/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/daily-notes/$noteId': {
      id: '/_authenticated/projects/$projectId/daily-notes/$noteId'
      path: '/projects/$projectId/daily-notes/$noteId'
      fullPath: '/projects/$projectId/daily-notes/$noteId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDailyNotesNoteIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/snippets/new-snippet': {
      id: '/_authenticated/projects/$projectId/snippets/new-snippet'
      path: '/new-snippet'
      fullPath: '/projects/$projectId/snippets/new-snippet'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSnippetsNewSnippetImport
      parentRoute: typeof AuthenticatedProjectsProjectIdSnippetsRouteImport
    }
    '/_authenticated/projects/$projectId/daily-notes/': {
      id: '/_authenticated/projects/$projectId/daily-notes/'
      path: '/projects/$projectId/daily-notes'
      fullPath: '/projects/$projectId/daily-notes'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDailyNotesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/snippets/': {
      id: '/_authenticated/projects/$projectId/snippets/'
      path: '/'
      fullPath: '/projects/$projectId/snippets/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSnippetsIndexImport
      parentRoute: typeof AuthenticatedProjectsProjectIdSnippetsRouteImport
    }
    '/_authenticated/projects/$projectId/summaries/': {
      id: '/_authenticated/projects/$projectId/summaries/'
      path: '/'
      fullPath: '/projects/$projectId/summaries/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSummariesIndexImport
      parentRoute: typeof AuthenticatedProjectsProjectIdSummariesRouteImport
    }
    '/_authenticated/projects/$projectId/todos/': {
      id: '/_authenticated/projects/$projectId/todos/'
      path: '/projects/$projectId/todos'
      fullPath: '/projects/$projectId/todos'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTodosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/snippets/$snippetId/edit': {
      id: '/_authenticated/projects/$projectId/snippets/$snippetId/edit'
      path: '/$snippetId/edit'
      fullPath: '/projects/$projectId/snippets/$snippetId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdEditImport
      parentRoute: typeof AuthenticatedProjectsProjectIdSnippetsRouteImport
    }
    '/_authenticated/projects/$projectId/snippets/$snippetId/': {
      id: '/_authenticated/projects/$projectId/snippets/$snippetId/'
      path: '/$snippetId'
      fullPath: '/projects/$projectId/snippets/$snippetId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexImport
      parentRoute: typeof AuthenticatedProjectsProjectIdSnippetsRouteImport
    }
    '/_authenticated/projects/$projectId/summaries/$summaryId/': {
      id: '/_authenticated/projects/$projectId/summaries/$summaryId/'
      path: '/$summaryId'
      fullPath: '/projects/$projectId/summaries/$summaryId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSummariesSummaryIdIndexImport
      parentRoute: typeof AuthenticatedProjectsProjectIdSummariesRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedProjectsProjectIdSnippetsRouteRouteChildren {
  AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute: typeof AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute
  AuthenticatedProjectsProjectIdSnippetsIndexRoute: typeof AuthenticatedProjectsProjectIdSnippetsIndexRoute
  AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute: typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute
  AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute: typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute
}

const AuthenticatedProjectsProjectIdSnippetsRouteRouteChildren: AuthenticatedProjectsProjectIdSnippetsRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute:
      AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute,
    AuthenticatedProjectsProjectIdSnippetsIndexRoute:
      AuthenticatedProjectsProjectIdSnippetsIndexRoute,
    AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute:
      AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute,
    AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute:
      AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdSnippetsRouteRouteWithChildren =
  AuthenticatedProjectsProjectIdSnippetsRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectIdSnippetsRouteRouteChildren,
  )

interface AuthenticatedProjectsProjectIdSummariesRouteRouteChildren {
  AuthenticatedProjectsProjectIdSummariesIndexRoute: typeof AuthenticatedProjectsProjectIdSummariesIndexRoute
  AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute: typeof AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute
}

const AuthenticatedProjectsProjectIdSummariesRouteRouteChildren: AuthenticatedProjectsProjectIdSummariesRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdSummariesIndexRoute:
      AuthenticatedProjectsProjectIdSummariesIndexRoute,
    AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute:
      AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdSummariesRouteRouteWithChildren =
  AuthenticatedProjectsProjectIdSummariesRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectIdSummariesRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjectsProjectIdSnippetsRouteRoute: typeof AuthenticatedProjectsProjectIdSnippetsRouteRouteWithChildren
  AuthenticatedProjectsProjectIdSummariesRouteRoute: typeof AuthenticatedProjectsProjectIdSummariesRouteRouteWithChildren
  AuthenticatedProjectsProjectIdDashboardRoute: typeof AuthenticatedProjectsProjectIdDashboardRoute
  AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute: typeof AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute
  AuthenticatedProjectsProjectIdDailyNotesIndexRoute: typeof AuthenticatedProjectsProjectIdDailyNotesIndexRoute
  AuthenticatedProjectsProjectIdTodosIndexRoute: typeof AuthenticatedProjectsProjectIdTodosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectsProjectIdSnippetsRouteRoute:
    AuthenticatedProjectsProjectIdSnippetsRouteRouteWithChildren,
  AuthenticatedProjectsProjectIdSummariesRouteRoute:
    AuthenticatedProjectsProjectIdSummariesRouteRouteWithChildren,
  AuthenticatedProjectsProjectIdDashboardRoute:
    AuthenticatedProjectsProjectIdDashboardRoute,
  AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute:
    AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute,
  AuthenticatedProjectsProjectIdDailyNotesIndexRoute:
    AuthenticatedProjectsProjectIdDailyNotesIndexRoute,
  AuthenticatedProjectsProjectIdTodosIndexRoute:
    AuthenticatedProjectsProjectIdTodosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/projects/$projectId/snippets': typeof AuthenticatedProjectsProjectIdSnippetsRouteRouteWithChildren
  '/projects/$projectId/summaries': typeof AuthenticatedProjectsProjectIdSummariesRouteRouteWithChildren
  '/projects/$projectId/dashboard': typeof AuthenticatedProjectsProjectIdDashboardRoute
  '/projects/$projectId/daily-notes/$noteId': typeof AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute
  '/projects/$projectId/snippets/new-snippet': typeof AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute
  '/projects/$projectId/daily-notes': typeof AuthenticatedProjectsProjectIdDailyNotesIndexRoute
  '/projects/$projectId/snippets/': typeof AuthenticatedProjectsProjectIdSnippetsIndexRoute
  '/projects/$projectId/summaries/': typeof AuthenticatedProjectsProjectIdSummariesIndexRoute
  '/projects/$projectId/todos': typeof AuthenticatedProjectsProjectIdTodosIndexRoute
  '/projects/$projectId/snippets/$snippetId/edit': typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute
  '/projects/$projectId/snippets/$snippetId': typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute
  '/projects/$projectId/summaries/$summaryId': typeof AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/projects/$projectId/dashboard': typeof AuthenticatedProjectsProjectIdDashboardRoute
  '/projects/$projectId/daily-notes/$noteId': typeof AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute
  '/projects/$projectId/snippets/new-snippet': typeof AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute
  '/projects/$projectId/daily-notes': typeof AuthenticatedProjectsProjectIdDailyNotesIndexRoute
  '/projects/$projectId/snippets': typeof AuthenticatedProjectsProjectIdSnippetsIndexRoute
  '/projects/$projectId/summaries': typeof AuthenticatedProjectsProjectIdSummariesIndexRoute
  '/projects/$projectId/todos': typeof AuthenticatedProjectsProjectIdTodosIndexRoute
  '/projects/$projectId/snippets/$snippetId/edit': typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute
  '/projects/$projectId/snippets/$snippetId': typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute
  '/projects/$projectId/summaries/$summaryId': typeof AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/projects/$projectId/snippets': typeof AuthenticatedProjectsProjectIdSnippetsRouteRouteWithChildren
  '/_authenticated/projects/$projectId/summaries': typeof AuthenticatedProjectsProjectIdSummariesRouteRouteWithChildren
  '/_authenticated/projects/$projectId/dashboard': typeof AuthenticatedProjectsProjectIdDashboardRoute
  '/_authenticated/projects/$projectId/daily-notes/$noteId': typeof AuthenticatedProjectsProjectIdDailyNotesNoteIdRoute
  '/_authenticated/projects/$projectId/snippets/new-snippet': typeof AuthenticatedProjectsProjectIdSnippetsNewSnippetRoute
  '/_authenticated/projects/$projectId/daily-notes/': typeof AuthenticatedProjectsProjectIdDailyNotesIndexRoute
  '/_authenticated/projects/$projectId/snippets/': typeof AuthenticatedProjectsProjectIdSnippetsIndexRoute
  '/_authenticated/projects/$projectId/summaries/': typeof AuthenticatedProjectsProjectIdSummariesIndexRoute
  '/_authenticated/projects/$projectId/todos/': typeof AuthenticatedProjectsProjectIdTodosIndexRoute
  '/_authenticated/projects/$projectId/snippets/$snippetId/edit': typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdEditRoute
  '/_authenticated/projects/$projectId/snippets/$snippetId/': typeof AuthenticatedProjectsProjectIdSnippetsSnippetIdIndexRoute
  '/_authenticated/projects/$projectId/summaries/$summaryId/': typeof AuthenticatedProjectsProjectIdSummariesSummaryIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/projects/$projectId/snippets'
    | '/projects/$projectId/summaries'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/daily-notes/$noteId'
    | '/projects/$projectId/snippets/new-snippet'
    | '/projects/$projectId/daily-notes'
    | '/projects/$projectId/snippets/'
    | '/projects/$projectId/summaries/'
    | '/projects/$projectId/todos'
    | '/projects/$projectId/snippets/$snippetId/edit'
    | '/projects/$projectId/snippets/$snippetId'
    | '/projects/$projectId/summaries/$summaryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/daily-notes/$noteId'
    | '/projects/$projectId/snippets/new-snippet'
    | '/projects/$projectId/daily-notes'
    | '/projects/$projectId/snippets'
    | '/projects/$projectId/summaries'
    | '/projects/$projectId/todos'
    | '/projects/$projectId/snippets/$snippetId/edit'
    | '/projects/$projectId/snippets/$snippetId'
    | '/projects/$projectId/summaries/$summaryId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/projects/$projectId/snippets'
    | '/_authenticated/projects/$projectId/summaries'
    | '/_authenticated/projects/$projectId/dashboard'
    | '/_authenticated/projects/$projectId/daily-notes/$noteId'
    | '/_authenticated/projects/$projectId/snippets/new-snippet'
    | '/_authenticated/projects/$projectId/daily-notes/'
    | '/_authenticated/projects/$projectId/snippets/'
    | '/_authenticated/projects/$projectId/summaries/'
    | '/_authenticated/projects/$projectId/todos/'
    | '/_authenticated/projects/$projectId/snippets/$snippetId/edit'
    | '/_authenticated/projects/$projectId/snippets/$snippetId/'
    | '/_authenticated/projects/$projectId/summaries/$summaryId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/projects/$projectId/snippets",
        "/_authenticated/projects/$projectId/summaries",
        "/_authenticated/projects/$projectId/dashboard",
        "/_authenticated/projects/$projectId/daily-notes/$noteId",
        "/_authenticated/projects/$projectId/daily-notes/",
        "/_authenticated/projects/$projectId/todos/"
      ]
    },
    "/_authenticated/projects/$projectId/snippets": {
      "filePath": "_authenticated/projects/$projectId/snippets/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/projects/$projectId/snippets/new-snippet",
        "/_authenticated/projects/$projectId/snippets/",
        "/_authenticated/projects/$projectId/snippets/$snippetId/edit",
        "/_authenticated/projects/$projectId/snippets/$snippetId/"
      ]
    },
    "/_authenticated/projects/$projectId/summaries": {
      "filePath": "_authenticated/projects/$projectId/summaries/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/projects/$projectId/summaries/",
        "/_authenticated/projects/$projectId/summaries/$summaryId/"
      ]
    },
    "/_authenticated/projects/$projectId/dashboard": {
      "filePath": "_authenticated/projects/$projectId/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/$projectId/daily-notes/$noteId": {
      "filePath": "_authenticated/projects/$projectId/daily-notes/$noteId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/$projectId/snippets/new-snippet": {
      "filePath": "_authenticated/projects/$projectId/snippets/new-snippet.tsx",
      "parent": "/_authenticated/projects/$projectId/snippets"
    },
    "/_authenticated/projects/$projectId/daily-notes/": {
      "filePath": "_authenticated/projects/$projectId/daily-notes/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/$projectId/snippets/": {
      "filePath": "_authenticated/projects/$projectId/snippets/index.tsx",
      "parent": "/_authenticated/projects/$projectId/snippets"
    },
    "/_authenticated/projects/$projectId/summaries/": {
      "filePath": "_authenticated/projects/$projectId/summaries/index.tsx",
      "parent": "/_authenticated/projects/$projectId/summaries"
    },
    "/_authenticated/projects/$projectId/todos/": {
      "filePath": "_authenticated/projects/$projectId/todos/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/$projectId/snippets/$snippetId/edit": {
      "filePath": "_authenticated/projects/$projectId/snippets/$snippetId/edit.tsx",
      "parent": "/_authenticated/projects/$projectId/snippets"
    },
    "/_authenticated/projects/$projectId/snippets/$snippetId/": {
      "filePath": "_authenticated/projects/$projectId/snippets/$snippetId/index.tsx",
      "parent": "/_authenticated/projects/$projectId/snippets"
    },
    "/_authenticated/projects/$projectId/summaries/$summaryId/": {
      "filePath": "_authenticated/projects/$projectId/summaries/$summaryId/index.tsx",
      "parent": "/_authenticated/projects/$projectId/summaries"
    }
  }
}
ROUTE_MANIFEST_END */
